package com.example.jdbc_timeout.model;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.departments
 */
public class Departments implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.departments.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.departments.date_created
     *
     * @mbg.generated
     */
    private LocalDateTime dateCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.departments.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.departments.last_updated
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.departments.id
     *
     * @return the value of public.departments.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.departments.id
     *
     * @param id the value for public.departments.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.departments.date_created
     *
     * @return the value of public.departments.date_created
     *
     * @mbg.generated
     */
    public LocalDateTime getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.departments.date_created
     *
     * @param dateCreated the value for public.departments.date_created
     *
     * @mbg.generated
     */
    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.departments.department_name
     *
     * @return the value of public.departments.department_name
     *
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.departments.department_name
     *
     * @param departmentName the value for public.departments.department_name
     *
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.departments.last_updated
     *
     * @return the value of public.departments.last_updated
     *
     * @mbg.generated
     */
    public LocalDateTime getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.departments.last_updated
     *
     * @param lastUpdated the value for public.departments.last_updated
     *
     * @mbg.generated
     */
    public void setLastUpdated(LocalDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}