package com.example.jdbc_timeout.mapper;

import com.example.jdbc_timeout.model.Departments;
import com.example.jdbc_timeout.model.DepartmentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface DepartmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    long countByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    int deleteByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    int insert(Departments row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    int insertSelective(Departments row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    List<Departments> selectByExampleWithRowbounds(DepartmentsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    List<Departments> selectByExample(DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    Departments selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Departments row, @Param("example") DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Departments row, @Param("example") DepartmentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Departments row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.departments
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Departments row);
}